name       : sdl1-net
version    : 1.2.8
release    : 1
source     :
    - https://www.libsdl.org/projects/SDL_net/release/SDL_net-1.2.8.tar.gz : 5f4a7a8bb884f793c278ac3f3713be41980c5eedccecff0260411347714facb4
license    : Zlib
summary    : SDL1 Networking
description: |
    SDL1 Networking
builddeps  :
    - pkgconfig(sdl)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
